### ISSUE TITLE
I followed the readme and got to localhost:3000 but it keeps asking me to log in and wont let me play any games

### ISSUE THREAD

**Issue by leomclaughlin4** [WarsWorld/WarsWorld#202]
I followed the readme and got to localhost:3000 without any errors, but then it keeps asking me to log in and everything fails to allow me to log in so I cannot play. Also is there a way to start a local game to pass and play with a friend?

**Comment by FunctionDJ** [comment]
There's no working frontend yet, the code that's there isn't connected with the backend. What gives you the impression that it should be playable? We're still far away from a beta or alpha phase.
Closing this issue because *of course* the project is still frequently in a broken state.
