### ISSUE TITLE
Add functionality to FeaturedNewsCard component in news page

### ISSUE THREAD

**Issue by rjam13** [WarsWorld/WarsWorld#210]
Currently, the long section above the three articles in the screenshot is just there to look pretty.

**Goal:**
I want that long section, the _FeaturedNewsCard_ component, to be the same as the articles cards(_LinkCard_ components) below. 

They should be exactly the same but they're just longer and grabs the viewers attention more.

Upon clicking, they should redirect the viewer to a valid article that corresponds to a markdown file in src/frontend/utils/articles/news

Feel free to experiment with the design and consult with the discord for opinions.

**Suggestions for implementation:**
- Mirror the logic found in src/frontend/components/layout/LinkCard.tsx. 
- Add a property called "isFeatured" in the markdown files to differentiate between articles to be rendered using _FeaturedNewsCard_ and articles to be rendered using _LinkCard_

![Screenshot 2024-01-05 at 12 51 19 PM](https://github.com/WarsWorld/WarsWorld/assets/89663000/59217da2-6aa4-4e5c-bc4f-9ee5bace5c2f)

**Comment by cliveglitch** [comment]
I wanna give it a try, later I'll show you a mock up when I get time. But I got a question, what makes an article the featured article? being the latest one? or something else?

**Comment by rjam13** [comment]
Personally, I think an article should be featured if we want it to be highlighted. E.g. important patch updates, content updates, future plans, etc. To do that, I am thinking of having a setting within the markdown files like "isFeatured" set to true. Then in the code, we separate those articles.

Or maybe create a subfolder within src/frontend/utils/articles/news to store the featured articles and then move them out when we don't want them to be featured anymore. This might be a better solution when taking paging into account.

Or we could just do it for the latest news article.

I am not sure what everyone wants and it isn't the biggest issue so whatever sensible approach is good imo.

**Comment by vimal20002** [comment]
Please assign this issue to me.It looks like one of my personal projects on Nextjs+Typescript

**Comment by rjam13** [comment]
Sorry, but I believe @cliveglitch is already on the issue

**Comment by cliveglitch** [comment]
Sorry, had to assigned myself on this but it's already done. 
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/88f2ed23-3f45-4f4e-a6c4-781a098d1888)

@vimal20002 feel free to comment on any other issue.
