### ISSUE TITLE
components/MatchCard <Link> Component Causes usePlayers Hook to Fail in [matchId].tsx

### ISSUE THREAD

**Issue by JaviTrek** [WarsWorld/WarsWorld#211]
### Description:
In components/MatchCard.tsx, replacing the `<a>` tag with Next.js's <Link> component causes an issue where the usePlayers hook, used in the match page, fails. This is unexpected behavior as `<Link>` should ideally enhance client-side navigation without impacting existing hooks or component functionality.

Code Snippet:
```ts
// Current implementation with <a> tag
<a href={`/match/${match.id}`} className="btnMenu @inline-block">
  Enter Match
</a>

// Intended implementation with <Link>
// TODO: Causes failure in usePlayers hook in [matchId] page
 <Link href={`/match/${match.id}`}>
   <a className="btnMenu @inline-block">Enter Match</a>
</Link>
```
### Expected Behavior:
Using `<Link>` for client-side navigation should not interfere with the usePlayers hook functionality.

### Actual Behavior:
Switching to `<Link>` disrupts the usePlayers hook, leading to failures on the match page.

### Steps to Reproduce:

- Replace the `<a>` tag with `<Link>` in components/MatchCard.tsx.
- Navigate to a match page.
- Observe the failure or incorrect behavior of the usePlayers hook.

The issue might be related to component lifecycle or state management with client-side navigation in Next.js.

**Comment by PalashChitnavis** [comment]
Hey, can I work on this issue?

**Comment by iampaandey** [comment]
Please assign this issue to me , I have been through these types of issues before ;-)

**Comment by JaviTrek** [comment]
> Please assign this issue to me , I have been through these types of issues before ;-)
> 
> 
> 
> 

I mean you can take it, I'll assign it to you. Do you have an idea of how long will you take?

**Comment by JaviTrek** [comment]
CliveG is a gigachad and solved this issue.
