### ISSUE TITLE
Store Articles in the database

### ISSUE THREAD

**Issue by rjam13** [WarsWorld/WarsWorld#212]
### Context

Since we are planning to add comments to articles, it would make the most sense to store articles in the database. 
Currently, article pages are wholly constructed from markdown files read from src/frontend/utils/articles. I am not sure on how comments would work with this implementation. 

### Suggested Actions

- Create an _Article_ model in schema.prisma
  - title as id (notice how the files names of the markdown files are the article titles)
  - a column to store the markdown file itself
  - create an [explicit many to many relationship](https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/many-to-many-relations) between the models _Article_ and _Player_ using a relation table similar to _ChatMessage_

- Create an _Article_ trpc router in src/server/routers
  - Translate all the functions found in src/frontend/utils/articleScript.ts to the router. 
    - instead of pulling the articles from a directory, the router would pull them from the database. 
    - instead of functions, the router would have procedures. 

- make the necessary changes to display the database articles on the website
  - if possible, keep both implementations of reading from the database and reading from src/frontend/utils/articles. 
 
I believe I covered everything, please comment below or message me in the discord server for suggestions/improvements in case I missed something. 

I plan on picking this up soon but anyone is open to pick it up in the meantime. 

I am always available for questions.

**Comment by cliveglitch** [comment]
I'm currently working on this, although there is already incomplete logic for this but called Post so I'm continuing that.

**Comment by cliveglitch** [comment]
Done.
