### ISSUE TITLE
Calculate unit/army value correctly

### ISSUE THREAD

**Issue by JaviTrek** [WarsWorld/WarsWorld#23]

**Comment by colorfularty** [comment]
I can take a crack at this. However, I don't see what parts of the code keep track of what units are on the map and where.

**Comment by FemboyDeveloper** [comment]
> I can take a crack at this. However, I don't see what parts of the code keep track of what units are on the map and where.

@colorfularty well we haven't finished the "dev environment" for pixi.js yet so I'd say please wait a couple of days/weeks for us to finally have it ready for other devs to work on it
