### ISSUE TITLE
setup of development environment does not work

### ISSUE THREAD

**Issue by cmdaltent** [WarsWorld/WarsWorld#239]
I performed the following steps as described in the README.md file.
1. created a `.env` file from `.env.example` and set secret strings for `PGPASSWORD` and `NEXTAUTH_SECRET`
2. `npm i`
3. `npm run db:up`
4. `npm run prisma:push`
5. `npm run prisma:seed`

Starting the local server using `npm run dev` everything seems to work at first, but opening `http://localhost:3000` causes the following error repeatedly, i.e., I already cleared everything and re-ran the steps, but the error persisted:

```
[next]  ⨯ ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[6].oneOf[14].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[6].oneOf[14].use[4]!./src/frontend/styles/global.scss
[next] Cannot read properties of undefined (reading 'indexOf')
[next]
[next] Import trace for requested module:
[next] ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[6].oneOf[14].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[6].oneOf[14].use[4]!./src/frontend/styles/global.scss
[next] ./src/frontend/styles/global.scss
[next]  ○ Compiling / ...
[next]  ⨯ ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[6].oneOf[14].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[6].oneOf[14].use[4]!./src/frontend/styles/global.scss
[next] Cannot read properties of undefined (reading 'pop')
[next]
[next] Import trace for requested module:
[next] ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[6].oneOf[14].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[6].oneOf[14].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[6].oneOf[14].use[4]!./src/frontend/styles/global.scss
[next] ./src/frontend/styles/global.scss
```

The first few lines of the error are also depicted in the browser instead of the landing page.

**Additional information**
- macOS 15.2 (M3)
- node 21.0.0

**Comment by JaviTrek** [comment]
@cmdaltent Strongly recommend to join our discord so we can help you more (thats where we are more active) https://discord.gg/M8NHSvVR

About the issue, from experience, I'm going to say this is a macOS issue (I'm not sure if we've had other devs using MacOS). I just did a minor update to our next.js config file. I'm not sure if it will help or not since I don't have MacOS.

If it doesn't help, strongly recommend you to try to troubleshoot it and see if you can make it work. Unsure whether it's the stack or your os or maybe node in your pc.

**Comment by cmdaltent** [comment]
Hello @JaviTrek,
the adjustment of yours in ac1071524f48fe340511f622c7dda86f6be55a45 indeed resolved the issue for me! Just to be sure, I cleaned up everything again and re-run the setup procedure, this time without any problems.
Therefore, I am going to close this issue. Thanks a ton for your help!
