### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by FemboyDeveloper** [WarsWorld/WarsWorld#70]
We need a banging home page! I'd like to imagine our homepage as either very catchy to the eye (a big image with a call to action at the beginning) and as a hub for information (should have small snippets/blocks of texts w images about our project. what we have, competition, etc.

**Comment by leekahung** [comment]
Still a work in progress, but I've started migrating what was previously done in the demo into the main app using NextJS layouts (shoutout JoncarlosT, I didn't knew of it until now) in my [forked branch](https://github.com/leekahung/WarsWorld/tree/migrating-layout-from-demo)

Here are some previews

![Screen Shot 2023-04-18 at 22 48 48](https://user-images.githubusercontent.com/14917816/232979353-15c80add-6985-4e1c-a6b6-3d42a249b8e1.png)

![Screen Shot 2023-04-18 at 22 49 03](https://user-images.githubusercontent.com/14917816/232979383-1aeb7d0a-aca5-48fd-b4dd-e5596a164dbc.png)

Of course there are still problems (see issue #4 and below), but we'll get there.

![Screen Shot 2023-04-18 at 22 49 18](https://user-images.githubusercontent.com/14917816/232979377-7bdbf7e9-2a49-489e-99f4-1b61e191140a.png)

**Comment by leekahung** [comment]
I think we can assign Frosty since he's already committing to the new Home Page.
