### ISSUE TITLE
Create responsive hamburger navbar

### ISSUE THREAD

**Issue by FemboyDeveloper** [WarsWorld/WarsWorld#78]
Allow our navbar to become responsive for mobile devices and make a hamburger menu. Below are some examples!

![Image](https://user-images.githubusercontent.com/96269542/236682799-1a730200-03a0-4ac1-8fdd-f57924cc6bf9.png)

![Image](https://user-images.githubusercontent.com/96269542/236682787-c5671c4e-0271-4e63-aed8-c9d54864a2f2.png)

**Comment by leekahung** [comment]
Should be implemented with PR #83

**Comment by leekahung** [comment]
Responsive hamburger menu updated in PR #89.

**Comment by FemboyDeveloper** [comment]
@leekahung are you sure you grabbed the correct PR number? That leads to a different location

**Comment by leekahung** [comment]
@FemboyDeveloper XD oops, you're right. it should be the previous one.

**Comment by leekahung** [comment]
Adding fixes to Navbar dropdown in PR #113 (now #116)

There was a typo to for Your Games, when being duplicated from Current Games.
