### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by JaviTrek** [WarsWorld/WarsWorld#79]
Don't think this needs alot of explanation, we need a good footer to guide people to different places inside our website. Below are some examples of what a good footer would look like

![Image](https://user-images.githubusercontent.com/96269542/236682665-3d432a51-f1c9-4ee4-baf2-5b284d45569f.png)

![Image](https://user-images.githubusercontent.com/96269542/236682694-673ece2c-c91c-44b5-ab5d-27a161df0da9.png)

![Image](https://user-images.githubusercontent.com/96269542/236682714-189dd104-0cff-49a6-afeb-5e078a9a0209.png)

**Comment by leekahung** [comment]
Similar to #80. The footer is being migrated from the demo in PR #83. Would likely need updates and edits after merge.
